#!/usr/bin/env bash

$HOME/.config/herbstluftwm/keybinds
$HOME/.config/herbstluftwm/theme
$HOME/.config/herbstluftwm/misc

# Set wallpaper
eval $(~/.fehbg)

# Start compositor
picom &

# Polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -q ws -r
