#!/usr/bin/env bash

hc() { herbstclient "$@"; }

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set always_show_frame off
hc set frame_border_width 0
hc set frame_transparent_width 0
hc set frame_gap 5

hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0

hc set window_gap 20
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
